spring:
  application:
    name: myagent
  profiles:
    active: default
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${myagent.data-dir}/${myagent.db-file}
  task:
    execution:
      pool:
        core-size: 8
        max-size: 20
        queue-capacity: 100
        keep-alive: 60s
        allow-core-thread-timeout: true

server:
  port: 8989

# MyBatis 配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

springdoc:
  packages-to-scan: ai.myagent
  paths-to-match: /**
  swagger-ui:
    operations-sorter: alpha
    default-model-expand-depth: 10

logging:
  file.path: ${myagent.data-dir}/logs
  config: classpath:logback-spring.xml
  level:
    root: info
    ai.myagent: info
    com.github.pagehelper.PageInterceptor: info

myagent:
  # 默认数据目录，目录下包含 SQLite 文件、config.yaml、skills目录、知识库文件上传目录等
  data-dir: ${user.home}/myagent
  db-file: data.sqlite       # 数据库文件名
  config-file: config.yaml   # Agent 配置文件名
  vec0-install-file: vec0-install.sh
  skills-dir: ${myagent.data-dir}/skills, ${user.home}/.agents/skills
  knowledge:
    vector-db-file: vectordb.json  # 向量数据库文件名
    upload-file-dir: files         # 知识库文件上传目录名
  env:
    # API_KEY 环境变量名
    openai-api-key: OPENAI_API_KEY
    deepseek-api-key: DEEPSEEK_API_KEY
    glm-api-key: GLM_API_KEY
    qwen-api-key: QWEN_API_KEY
  session-default:
    title: Untitled
    prompt-summary: "将以上对话内容总结为标题，尽量控制在20个字以内，不得超过30个字"
